version: "3"
services:
  pico:
    container_name: pico
    tty: true
    user: "1000:1000"
    build:
      context: ./pico
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - "./pico/work:/home/ubuntu/work"

